services:
  webserver:
    image: kheidencom:gemini-developer-contest-aug-2024
    networks:
      - custom_network
    volumes:
      - ./src:/app/src
      - ./logs:/var/log/gunicorn
    ports:
      - "4867:4867"
    env_file:
      - .env
    restart: always

networks:
  custom_network:
    driver: bridge